# Generated by Django 4.0.6 on 2022-09-23 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=60)),
                ('sexo', models.CharField(blank=True, max_length=9, null=True)),
                ('documento', models.CharField(max_length=10)),
                ('fechaNacimiento', models.CharField(max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('estadoCivil', models.CharField(max_length=11)),
                ('numeroHijos', models.CharField(max_length=2)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('idCitas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=10)),
                ('servicio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Citas', to='Citas.clientes')),
            ],
        ),
    ]
